### ISSUE TITLE
0.8 Roadmap

### ISSUE THREAD

**Issue by Qstick** [lidarr/Lidarr#953]
Break the artist folder reliance. 

  - [ ] Turn Artists into "import list like" entity, that is used to add new albums if the artist is "followed"
    - Will allow ability to have files from same artist in different root folders
    - Will allow more customized naming and organization of files.

Use Track identification to add new albums/artists on import.

- [x] Eliminate mapping of artists at import. One click root folder adding. Lidarr scans for audio tracks, adds all to DB and tries matching them as it goes. 

- [x] Add ability to add single albums, which will add the related artist as a "unfollowed" artist that user can later decide to follow if wanted

- [x] Blacklist certain artists from being followed (various, etc) to prevent 10,000 albums from being added at once

Naming/Organization Changes

- [ ] Eliminate "Album Folder" setting for artists (DB Migration) (#1582)

- [ ] Change Album Folder, ~Artist Folder~Track naming to be one naming field pattern that can use any tokens (#1582)

- [x] Add a multi-disk naming pattern and/or naming profiles to allow different naming patterns for different artists

- [x] Either add the default root folder setting in naming profile or in artist so that we know where to store new albums

**Comment by SiemdeNijs** [comment]
This all sounds wonderful, more customization options, but building upon track matching may require better track matching first ? 

Currently, the que will always be cluttered with things that have to be manually imported, even though the files are 1:1 matching.  The process of track matching after import sounds like even more manual work if improving track-matching isn't a priority ?

**Comment by ta264** [comment]
Matching seems pretty accurate to me as long as the data is on musicbrainz. Jump on the discord channel and we can try to figure out your issue (or discover there's an actual bug)

**Comment by SiemdeNijs** [comment]
> Matching seems pretty accurate to me as long as the data is on musicbrainz. Jump on the discord channel and we can try to figure out your issue (or discover there's an actual bug)

Thanks for the reply, I will do that soon, I'd love to help diagnose this strange behavior.
I have a library of legally-bought media with corresponding metadata; even this will get negative matches at the moment upon import. 

I'll be on the discord soon, kind regards.

**Comment by tbrasser** [comment]
Hey guys, this seems as if it would open up Lidarr for Mix and VA albums, right? Awesome!

**Comment by Qstick** [comment]
Correct

**Comment by minakitty** [comment]
Thank goodness, I'm setting up my library and seeing all these OST/compilation albums that are going to be so lonely

**Comment by ChaosBlades** [comment]
This issue is over a year old now and the last update on the develop branch will be 1 year old tomorrow. I see commits have been made as recently as 2 days ago so what exactly has been the hold up on pushing a new update?

**Comment by Qstick** [comment]
Ensuring 40k instances don't corrupt or get stranded on pushing....

**Comment by cooperaj** [comment]
Is this in yet? I've been trying to figure out OST's thinking it was in based on this issue being older.
